version: "3.8"

services:
  db:
    image: postgres:13
    container_name: taski_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: fertikylyapka/taski_backend:latest
    container_name: taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    restart: always

  frontend:
    image: fertikylyapka/taski_frontend:latest
    container_name: taski_frontend
    restart: always

  gateway:
    image: fertikylyapka/taski_gateway:latest
    container_name: taski_gateway
    depends_on:
      - backend
      - frontend
    ports:
      - "8001:80"
    volumes:
      - static:/static
      - media:/media
    restart: always

volumes:
  pg_data:
  static:
  media:
